# Generated by Django 5.1.4 on 2025-02-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='data',
            field=models.TextField(),
        ),
    ]
